In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame(np.random.rand(10, 10), columns=list('ABCDEFGHIJ')) * 10**7
df

,A,B,C,D,E,F,G,H,I,J
0,7.185917e+06,1.898680e+06,8.559152e+06,6.467466e+06,1.354230e+06,4.935422e+06,4.203680e+06,7.212383e+06,2.165359e+06,5.236440e+06
1,1.458406e+06,4.387591e+06,2.655780e+06,4.351074e+06,7.259367e+06,2.510267e+06,8.622930e+06,1.426475e+06,3.552837e+06,8.278566e+06
2,6.212476e+06,4.126049e+06,6.848307e+06,7.227176e+06,8.664449e+06,4.067298e+05,4.237244e+06,5.249348e+06,2.890431e+06,6.765472e+06
3,2.337154e+06,1.098136e+06,4.009220e+06,9.803311e+06,1.306166e+06,8.549947e+05,9.515346e+06,5.879958e+06,2.440901e+06,6.403621e+06
4,2.052663e+06,8.845251e+06,5.800530e+05,3.375020e+05,4.915520e+06,5.454618e+06,7.239360e+06,4.919389e+05,5.417191e+06,1.869248e+06
5,9.420784e+06,4.183468e+06,6.566999e+06,7.929240e+06,4.254634e+05,1.373791e+06,3.061949e+06,6.284632e+06,2.786494e+05,2.241313e+06
6,1.625912e+06,3.587928e+06,6.647600e+06,8.762467e+06,3.298594e+06,4.272221e+06,7.815525e+06,4.441663e+06,7.119722e+06,4.081421e+05
7,4.075684e+06,4.236281e+06,5.755465e+05,6.641514e+06,8.324524e+06,7.981302e+06,1.044166e+06,6.378662e+04,6.203922e+06,3.659234e+06
8,1.410785e+06,3.648447e+06,1.767731e+06,8.115813e+06,8.433291e+06,5.847000e+06,2.825943e+06,2.575784e+06,9.579325e+06,5.079805e+06
9,3.809965e+06,4.450504e+06,6.223885e+06,6.757665e+06,5.331363e+06,9.334193e+06,1.725900e+06,5.192276e+06,2.436415e+06,8.680667e+06

In [3]:
# supress scientific notation and control decimal points shown with float_format
pd.options.display.float_format  = '{:.2f}'.format
df

,A,B,C,D,E,F,G,H,I,J
0,7185917.11,1898679.93,8559152.24,6467466.13,1354230.00,4935421.81,4203679.65,7212383.08,2165359.19,5236440.22
1,1458406.14,4387590.50,2655779.68,4351074.03,7259366.86,2510266.79,8622930.44,1426474.70,3552836.86,8278565.93
2,6212475.73,4126049.46,6848307.36,7227175.70,8664448.54,406729.78,4237243.69,5249347.81,2890430.94,6765471.59
3,2337153.91,1098135.87,4009220.15,9803310.55,1306165.51,854994.74,9515346.11,5879958.23,2440901.48,6403620.93
4,2052663.44,8845251.22,580052.98,337502.05,4915520.01,5454617.90,7239359.74,491938.85,5417191.24,1869248.35
5,9420783.85,4183467.85,6566998.52,7929240.47,425463.36,1373790.84,3061948.53,6284631.72,278649.35,2241312.96
6,1625912.08,3587928.48,6647600.10,8762467.48,3298593.95,4272220.59,7815524.61,4441663.35,7119722.14,408142.12
7,4075683.74,4236280.81,575546.48,6641513.80,8324523.70,7981301.85,1044165.97,63786.62,6203921.62,3659233.90
8,1410785.28,3648447.37,1767731.49,8115813.02,8433290.93,5847000.45,2825942.81,2575783.96,9579325.44,5079804.73
9,3809965.14,4450503.99,6223884.74,6757665.21,5331362.78,9334192.56,1725900.49,5192276.44,2436414.75,8680667.33

In [4]:
# control max rows and columns
pd.options.display.max_rows = 4
pd.options.display.max_columns = 4
df

            A          B  ...          I          J
0  7185917.11 1898679.93  ... 2165359.19 5236440.22
1  1458406.14 4387590.50  ... 3552836.86 8278565.93
..        ...        ...  ...        ...        ...
8  1410785.28 3648447.37  ... 9579325.44 5079804.73
9  3809965.14 4450503.99  ... 2436414.75 8680667.33

[10 rows x 10 columns]

In [5]:
# large_repr lets you select whether to display dataframes that exceed max_columns or max_rows
# as a truncated frame ('truncate'), or as a summary ('info'). 'truncate' is default
pd.options.display.large_repr = 'info'
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
A    10 non-null float64
B    10 non-null float64
C    10 non-null float64
D    10 non-null float64
E    10 non-null float64
F    10 non-null float64
G    10 non-null float64
H    10 non-null float64
I    10 non-null float64
J    10 non-null float64
dtypes: float64(10)
memory usage: 928.0 bytes

In [6]:
# reset options
pd.reset_option('all', silent=True)
df.head()

,A,B,C,D,E,F,G,H,I,J
0,7.185917e+06,1.898680e+06,8.559152e+06,6.467466e+06,1.354230e+06,4.935422e+06,4.203680e+06,7.212383e+06,2.165359e+06,5.236440e+06
1,1.458406e+06,4.387591e+06,2.655780e+06,4.351074e+06,7.259367e+06,2.510267e+06,8.622930e+06,1.426475e+06,3.552837e+06,8.278566e+06
2,6.212476e+06,4.126049e+06,6.848307e+06,7.227176e+06,8.664449e+06,4.067298e+05,4.237244e+06,5.249348e+06,2.890431e+06,6.765472e+06
3,2.337154e+06,1.098136e+06,4.009220e+06,9.803311e+06,1.306166e+06,8.549947e+05,9.515346e+06,5.879958e+06,2.440901e+06,6.403621e+06
4,2.052663e+06,8.845251e+06,5.800530e+05,3.375020e+05,4.915520e+06,5.454618e+06,7.239360e+06,4.919389e+05,5.417191e+06,1.869248e+06